#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $CUSTOM_DB_USER WITH PASSWORD '$CUSTOM_DB_PASSWORD';
    CREATE DATABASE $CUSTOM_DB_NAME OWNER $CUSTOM_DB_USER;
EOSQL
